### ISSUE TITLE
execvp failed: No such file or directory

### ISSUE THREAD

**Issue by piotr-yuxuan** [sorah/envchain#13]
Hello,

Thanks for you work :-) However, envchain sometimes fails unexcpetedly. For instance:

``` bash
$ envchain ns eval "echo 1"
#=> execvp failed: No such file or directory
```

It fails for any namespace.

**Comment by sorah** [comment]
Because it doesn't use a shell. Your command line finds `eval` command from your `$PATH`.

You should do `envchain ns sh -c 'echo 1'` (or maybe `bash -c`) to run a shell instead.

**Comment by piotr-yuxuan** [comment]
Thanks, great! Actually I was much more trying to load an namespace at terminal bootstrap than echoing a number ^^

Your message lead me to find `login -pfq Alice zsh -c "envchain ns zsh"` can achieve so. Methinks `.profile` and `.zshrc`are read only once but I'd gladly welcome any further idea :-)

**Comment by sorah** [comment]
I have not tried to do so, and It doesn't resolve a issue that envchain targets, I do no recommend. envchain is to allow selecting secret environment variables for each commands to human.

**Comment by petemounce** [comment]
I also have this error, when I try in a shell (zsh) to run a command having just set a namespace:
```
$ envchain my-ns-with-dashes aws ec2 describe-amis
execvp failed: No such file or directory
```

**Comment by sorah** [comment]
This would be different problem, but I strongly believe it have wrong configuration on your shell environment. At least I use namespace including dashes and experiencing no problem.

The error shows envchain couldn't find `aws` from your `$PATH` environment variable.

**Comment by petemounce** [comment]
Thanks; you were right. Totally user error, it wasn't installed.
