### ISSUE TITLE
Usage with direnv?

### ISSUE THREAD

**Issue by olalonde** [sorah/envchain#14]
I was wondering what would be the best way to use envchain with direnv? Basically, I'd like to hide some values in my .envrc files and was wondering if this would now be possible with envchain.

**Comment by prognostikos** [comment]
@olalonde here's how I integrate the two - this is what I use in my `.envrc` per project:

```bash
ENVCHAIN_NAMESPACE=project1
export $(comm -1 -3 <(env|sort) <(envchain "$ENVCHAIN_NAMESPACE" env|sort))
```

It's kind of terse, but basically it just ensures that I only export the variables stored in envchain instead of re-exporting all of my environment.

**Comment by sorah** [comment]
Personally speaking I hate direnv way to set environment variables. I won't write any supports for direnv.

Principle and design in `envchain` is to make a scope of environment variables more explicitly.

**Comment by blalor** [comment]
Old comment issue, I know, but I just wrote up how I've been using envchain with direnv (for years): https://github.com/direnv/direnv/wiki/envchain
