### ISSUE TITLE
Setting variables from script programmatically

### ISSUE THREAD

**Issue by endorama** [sorah/envchain#15]
Hello, thanks for the cool project!

I'd like to set variables from a script, in a fashion similar to:

```
# do some stuff to get/generate values
envchain -s foo BAR <<VALUE_HERE>>
```

From the readme this doesn't seem to be possible, but I was wandering if I'm missing something.

I could write a little wrapper that replies to envchain prompts, but it seems a bit too hackish!

Thanks

**Comment by endorama** [comment]
I found that passing variable to `STDIN` works as expected, so I can do something on the line of:

```
echo "<<VALUE_HERE>>" | envchain -s foo BAR
```

I'm going to close this.

**Comment by sorah** [comment]
Hi, sorry for being late to reply...

Your solution is correct.

By design, `envchain` expects given values are sensitive and should be secured. So, I won't make `envchain` accepts values in command line, since command line is visible from other users, in macOS and Linux.
