### ISSUE TITLE
multiline variable support

### ISSUE THREAD

**Issue by sjwl** [sorah/envchain#20]
I'd like to store multiline secrets (e.g. - ~/.ssh/id_rsa) to envchain.  Unfortunately, running this doesn't work:
```
cat ~/.ssh/id_rsa | envchain -s foo my_private_key
```
`my_private_key` only stores the top line
```
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by drebes** [comment]
I had a similar issue trying to set `GOOGLE_CREDENTIALS` to the contents of the JSON file for my Google Cloud service account key. Only the first line ("{") gets imported. Fortunately changing the variable contents to the multi-line value directly on Keychain Access (macOS) works, but it would be nice to do it from the command line.

**Comment by haakonstorm** [comment]
<img width="953" alt="Screenshot of iTerm2 (22-04-2021, 00-50-35)" src="https://user-images.githubusercontent.com/193781/115630701-c1b51980-a304-11eb-888d-d7326080d27c.png">

**Comment by haakonstorm** [comment]
## encode to plain hexdump, swap newlines with dashes, write with envchain
´´´
< id_rsa | xxd -p -u - | tr '\n' '-' | envchain -s foo my_private_key
´´´

## read with envchain, swap dashes back to newlines, decode plain hexdump
```
envchain foo /bin/bash -c 'echo $my_private_key' | tr '-' '\n' | xxd -p -u -r - > id_rsa.restored
```

**Comment by tddschn** [comment]
@sjwl Just curious, why do you want to store the content of private keys in the keychain?
Can you remove the `id_rsa` file and still make ssh work?

**Comment by tddschn** [comment]
@haakonstorm Thanks for the one-liners! 
How would you conveniently inject a multiline env var into a command?

**Comment by haakonstorm** [comment]
@tddschn thanks for the feedback! I'm not sure how to suggest anything without any context :). It really depends on which program you are feeding your multiline variable, and how you want and can feed it. We are moving fast towards quotation shell hell here :)

**Comment by sorah** [comment]
IIRC some secret providers don't support return characters, so I am not going to directly support this.

**Comment by tddschn** [comment]
@haakonstorm Thanks for the comment! I find turnning newlines into literal ones (`\n`s) and then feeding them to `envchain` quite useful for my use cases. :)
