### ISSUE TITLE
How to retrieve secrets stored in envchain

### ISSUE THREAD

**Issue by SRAHEJA86** [sorah/envchain#36]
This article explains how to store secrets in the envchain, however there is no guidance how to retrieve those values - if they're to be used in an application . 
This example here explains storing AWS secrets to envchain - 
```

$ envchain --set aws AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
aws.AWS_ACCESS_KEY_ID: my-access-key
aws.AWS_SECRET_ACCESS_KEY: secret
```
However there are no steps which can explain how these secrets can be used in a application config file - say a Java spring boot or Node JS application

**Comment by sorah** [comment]
https://github.com/sorah/envchain?tab=readme-ov-file#execute-commands-with-defined-variables

- envchain is very simple tool: Store environment variables to backend (e.g. Keychain in macOS) then expose the stored values through environment variables. It is up to users to integrate environment variables in their code/application/scripts/whatever.
- for cases that a human wants to check which values are stored in which namespace, for instance in macOS, they can use Keychain Access.
